#!/usr/bin/env zsh

osascript -e 'display notification "Install App Store apps.\nYou should login first."'
open -a "App Store"
echo 'WARNING: You should login App Store before install Mac Apps.'
echo 'Press any key to continue...'; read -n -s

# install com.sindresorhus.Dato
mas install 1470584107 > /dev/null &

# install net.shinyfrog.bear
mas install 1091189122 > /dev/null &

# install jp.naver.line.mac
mas install 539883307 > /dev/null &

# install com.apple.iWork.Keynote
mas install 409183694 > /dev/null &

# install com.apple.iWork.Numbers
mas install 409203825 > /dev/null &

# install com.apple.iWork.Pages
mas install 409201541 > /dev/null &

# install ru.keepcoder.Telegram
mas install 747648890 > /dev/null &

# install com.apple.dt.Xcode
mas install 497799835 > /dev/null &

# install com.apple.FinalCut
mas install 424389933 > /dev/null &

# install com.apple.motionapp
mas install 434290957 > /dev/null &

# install com.apple.iMovieApp
mas install 408981434 > /dev/null &

# install com.ulyssesapp.mac
mas install 1225570693 > /dev/null &

# install de.APPenzeller.Pipifier
mas install 1160374471 > /dev/null &

# install Telegram
mas install 747648890 > /dev/null &

# install Slack
mas install 803453959 > /dev/null &

# install Jira Cloud by Atlassian
mas install 1475897096 > /dev/null &

# install Anki Notes: Flashcards Maker
mas install 1503902660 > /dev/null &

# install AdBlock Pro for Safari
mas install 1018301773 > /dev/null &

# install AdBlock for Safari
mas install 1402042596 > /dev/null &
