#!/usr/bin/env bash

# install com.apple.FinalCut
mas install 424389933

# install jp.naver.line.mac
mas install 539883307

# install com.apple.iWork.Keynote
mas install 409183694

# install ru.keepcoder.Telegram
mas install 747648890

# install cx.c3.theunarchiver
mas install 425424353

# install com.agilebits.onepassword-osx
mas install 443987910

# install com.apple.motionapp
mas install 434290957

# install com.apple.iWork.Numbers
mas install 409203825

# install com.apple.dt.Xcode
mas install 497799835

# install com.apple.iWork.Pages
mas install 409201541

# install net.shinyfrog.bear
mas install 1091189122

# install com.apple.iMovieApp
mas install 408981434

# install com.tinyspeck.slackmacgap
mas install 803453959

# install com.microsoft.rdc.macos
mas install 1295203466

# install com.ulyssesapp.mac
mas install 1225570693

# install com.apple.Compressor
mas install 424390742

osascript -e 'tell application "System Events" to make login item at end with properties {name: "Alfred 3", path:"/Applications/Alfred 3.app", hidden:false}'
osascript -e 'tell application "System Events" to make login item at end with properties {name: "Backup and Sync from Google", path:"/Applications/Backup and Sync from Google.app", hidden:false}'
osascript -e 'tell application "System Events" to make login item at end with properties {name: "Bear", path:"/Applications/Bear.app", hidden:false}'
osascript -e 'tell application "System Events" to make login item at end with properties {name: "Line", path:"/Applications/Line.app", hidden:false}'
osascript -e 'tell application "System Events" to make login item at end with properties {name: "Slack", path:"/Applications/Slack.app", hidden:false}'
osascript -e 'tell application "System Events" to make login item at end with properties {name: "Spectacle", path:"/Applications/Spectacle.app", hidden:false}'
