#!/usr/bin/env zsh

brew cask install appcleaner
brew cask install authy
brew cask install docker
brew cask install firefox
brew cask install github
brew cask install google-backup-and-sync
brew cask install grammaly
brew cask install iterm2
brew cask install karabiner-elements
brew cask install makemkv
brew cask install spectacle
brew cask install tripmode
brew cask install visual-studio-code

code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
