#!/usr/bin/env zsh

osascript -e 'display notification "Install cask apps"'

brew install --cask balance-lock        # to prevent changing left-right balance
brew install --cask chatgpt
brew install --cask claude
brew install --cask claude-code
brew install --cask figma
brew install --cask flutter
brew install --cask github
brew install --cask google-chrome
brew install --cask jordanbaird-ice
brew install --cask karabiner-elements
brew install --cask keymapp
brew install --cask makemkv
brew install --cask monitorcontrol
brew install --cask notion
brew install --cask notion-calendar
brew install --cask obsidian
brew install --cask raycast
brew install --cask sf-symbols
brew install --cask steam
brew install --cask syntax-highlight    # to support syntax highlighting in Quick Look
brew install --cask tailscale
brew install --cask visual-studio-code
brew install --cask warp
brew install --cask zoom
