#!/usr/bin/env zsh

osascript -e 'display notification "Install libraries"'

brew install colima
brew install direnv
brew install docker
brew install docker-compose
brew install ffmpeg
brew install mas
brew install mediainfo
brew install mkvtoolnix
brew install peco
brew install pyenv

brew install withgraphite/tap/graphite
