#!/usr/bin/env zsh

osascript -e 'display notification "Install libraries"'

brew install colima
brew install docker
brew install ffmpeg
brew install kubernetes-cli
brew install mas
brew install mediainfo
brew install mkvtoolnix
brew install peco
