#!/usr/bin/env bash

xcode-select --install
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update
brew upgrade

brew install mas
brew install python3
brew install peco
brew install rsync

brew cleanup
