#!/usr/bin/env zsh

osascript -e 'display notification "Install cask apps"'

brew install --cask antigravity-cli
brew install --cask antigravity-ide
brew install --cask balance-lock
brew install --cask chatgpt
brew install --cask claude
brew install --cask claude-code
brew install --cask codex
brew install --cask github
brew install --cask google-chrome
brew install --cask jordanbaird-ice
brew install --cask karabiner-elements
brew install --cask monitorcontrol
brew install --cask notion
brew install --cask notion-calendar
brew install --cask obsidian
brew install --cask orbstack
brew install --cask postico
brew install --cask raycast
brew install --cask steam
brew install --cask syntax-highlight
brew install --cask tailscale
brew install --cask typora
brew install --cask visual-studio-code
brew install --cask warp
