#!/usr/bin/env zsh

###############################################################################
# VS Code                                                                     #
###############################################################################
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension github.copilot

###############################################################################
# Login Items                                                                 #
###############################################################################
defaults write com.knollsoft.Rectangle launchOnLogin -bool true
