#!/usr/bin/env zsh

# VS Code
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension github.copilot

# Login Items
open -a "Alfred 5"
open -a "Balance Lock"
open -a "Bartender 4"
open -a "Notion Calendar"
open -a Rectangle

# Change Downloads folder to iCloud Drive
sudo rm -rf ~/Downlaods; ln -s ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Downloads/ ~/
