#!/usr/bin/env bash

############
# generals #
############

brew install direnv

##########
# python #
##########

brew install pyenv
brew install pyenv-virtualenv

#############
# terraform #
#############

brew install tfenv
